#Question:
#Take any two matrices of suitable order and perform following operations
1. Addition
2. Substraction
3. Multiplication
4. Transpose
5. find inverse for each matrix


In [ ]:
import numpy as np
import sympy as sy
sy.init_printing()

In [ ]:
def round_expr(expr, num_digits):
    return expr.xreplace({n : round(n, num_digits) for n in expr.atoms(sy.Number)})

# <font face="gotham" color="purple"> Matrix Operations</font>

Matrix _addition_ operations are straightforward:
1. $A+ B= B+ A$
2. $(A+B)+ C=A+(B+C)$
3. $c(A+B)=cA+cB$
4. $(c+d)A=cA+c{D}$
5. $c(dA)=(cd)A$
6. $A+{0}=A$, where ${0}$ is the zero matrix
7. For any $A$, there exists an $- A$, such that $ A+(- A)=0$.

They are as obvious as it looks, so no proofs are provided. And the matrix _multiplication_ properties are:
1. $ A({BC})=({AB}) C$
2. $c({AB})=(cA)B=A(cB)$
3. $A(B+ C)={AB}+{AC}$
4. $(B+C)A={BA}+{CA}$

Note that we need to differentiate between two types of multiplication: _Hadamard multiplication_, denoted as $A \odot B$ (element-wise multiplication), and _matrix multiplication_, denoted simply as $AB$.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
A*B # this is Hadamard elementwise product

array([[ 5, 12],
       [21, 32]])

In [ ]:
A@B # this is matrix product

array([[19, 22],
       [43, 50]])

## <font face="gotham" color="purple"> SymPy Demonstration: Addition </font>

Let's define all the letters as symbols in case we need to use them repeatedly. With this library, we can perform computations analytically, making it a valuable tool for learning linear algebra.

In [ ]:
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z = sy.symbols('a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z', real = True)

In [ ]:
A = sy.Matrix([[a, b, c], [d, e, f]])
A + A
A - A

⎡2⋅a  2⋅b  2⋅c⎤
⎢             ⎥
⎣2⋅d  2⋅e  2⋅f⎦

⎡0  0  0⎤
⎢       ⎥
⎣0  0  0⎦

In [ ]:
B = sy.Matrix([[g, h, i], [j, k, l]])
A + B

A - B

⎡a + g  b + h  c + i⎤
⎢                   ⎥
⎣d + j  e + k  f + l⎦

⎡a - g  b - h  c - i⎤
⎢                   ⎥
⎣d - j  e - k  f - l⎦

## <font face="gotham" color="purple"> SymPy Demonstration: Multiplication </font>

The matrix multiplication rules can be clearly understood by using symbols.

In [ ]:
A = sy.Matrix([[a, b, c], [d, e, f]])
B = sy.Matrix([[g, h, i], [j, k, l], [m, n, o]])
A
B

⎡a  b  c⎤
⎢       ⎥
⎣d  e  f⎦

⎡g  h  i⎤
⎢       ⎥
⎢j  k  l⎥
⎢       ⎥
⎣m  n  o⎦

In [ ]:
AB = A*B; AB

⎡a⋅g + b⋅j + c⋅m  a⋅h + b⋅k + c⋅n  a⋅i + b⋅l + c⋅o⎤
⎢                                                 ⎥
⎣d⋅g + e⋅j + f⋅m  d⋅h + e⋅k + f⋅n  d⋅i + e⋅l + f⋅o⎦

## <font face="gotham" color="purple"> Commutability </font>

Matrix multiplication usually does not commute, meaning ${AB} \neq {BA}$. For instance, consider matrices $A$ and $B$:

In [ ]:
A = sy.Matrix([[3, 4], [7, 8]])
B = sy.Matrix([[5, 3], [2, 1]])
A*B
B*A

⎡23  13⎤
⎢      ⎥
⎣51  29⎦

⎡36  44⎤
⎢      ⎥
⎣13  16⎦

How do we find a commutable matrix? Let's try find out analytically

In [ ]:
A = sy.Matrix([[a, b], [c, d]])
B = sy.Matrix([[e, f], [g, h]])
A*B
B*A

⎡a⋅e + b⋅g  a⋅f + b⋅h⎤
⎢                    ⎥
⎣c⋅e + d⋅g  c⋅f + d⋅h⎦

⎡a⋅e + c⋅f  b⋅e + d⋅f⎤
⎢                    ⎥
⎣a⋅g + c⋅h  b⋅g + d⋅h⎦

# <font face="gotham" color="purple"> Transpose of Matrices </font>

Matrix $A_{n\times m}$ and its transpose is

In [ ]:
A = sy.Matrix([[1, 2, 3], [4, 5, 6]]); A
A.transpose()

⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

⎡1  4⎤
⎢    ⎥
⎢2  5⎥
⎢    ⎥
⎣3  6⎦

The properties of transpose are
1. $(A^T)^T$
2. $(A+B)^T=A^T+B^T$
3. $(cA)^T=cA^T$
4. $(AB)^T=B^TA^T$

We can show why the last property holds with SymPy, define $A$ and $B$, multiply them, then transpose, that means $(AB)^T$

In [ ]:
A = sy.Matrix([[a, b], [c, d], [e, f]])
B = sy.Matrix([[g, h, i], [j, k, l]])
AB = A*B
AB_t = AB.transpose(); AB_t

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

Transpose $A$ and $B$, then multiply, meaning $B^TA^T$

In [ ]:
B_t_A_t = B.transpose()*A.transpose()
B_t_A_t

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

Check if they are equal

In [ ]:
AB_t == B_t_A_t

True

# <font face="gotham" color="purple"> Identity Matrices </font>

This is an identity matrix $I_5$, only $1$'s on principal diagonal, all rest elements are $0$'s.

In [ ]:
sy.eye(5)

⎡1  0  0  0  0⎤
⎢             ⎥
⎢0  1  0  0  0⎥
⎢             ⎥
⎢0  0  1  0  0⎥
⎢             ⎥
⎢0  0  0  1  0⎥
⎢             ⎥
⎣0  0  0  0  1⎦

Identity matrix properties:

$$
AI=IA = A
$$

Let's generate $ I$ and $ A$ and show if it holds

In [ ]:
I = np.eye(5); I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
A = np.around(np.random.rand(5, 5)*100); A # generate a random matrix

array([[42., 73., 33., 12., 98.],
       [28., 33., 18., 45., 19.],
       [47., 92., 58., 54., 15.],
       [43., 16., 51., 58., 75.],
       [27., 71., 16., 17.,  6.]])

Check if they are equal

In [ ]:
(A@I == I@A).all()

True

# <font face="gotham" color="purple"> Inverse Matrices </font>

If ${AB}={BA}=\mathbf{I}$, $ B$ is called the inverse of matrix $  A$, denoted as $ B=  A^{-1}$.


NumPy has convenient function ```np.linalg.inv()``` for computing inverse matrices. Generate $ A$

In [ ]:
A = np.round(10*np.random.randn(5,5)); A

array([[-10., -14.,  16.,   3.,  -7.],
       [  1.,  -3.,   9.,   5.,   0.],
       [-15.,   2.,  -8.,  17.,  15.],
       [ 23.,  -7.,  -6., -21.,  -7.],
       [ 18.,   2.,  18.,  -6., -12.]])

In [ ]:
Ainv = np.linalg.inv(A); Ainv

array([[ 0.131, -0.442,  0.357,  0.116,  0.302],
       [-0.157,  0.346, -0.286, -0.115, -0.198],
       [-0.336,  1.136, -0.736, -0.2  , -0.608],
       [ 0.483, -1.549,  1.082,  0.267,  0.915],
       [-0.575,  1.873, -1.158, -0.278, -1.032]])

Verify if they are truly inverse of each other

In [ ]:
A@Ainv

array([[ 1.,  0.,  0., -0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0., -0., -0.,  1., -0.],
       [ 0., -0., -0., -0.,  1.]])

The ```-0.``` means there are more digits after point, but omitted here.